### ISSUE TITLE
GMSEC 4.9.1 error on load

### ISSUE THREAD

**Issue by bpfoster** [nasa/GMSEC_API#34]
From what I can see, yesterday [some changes](https://github.com/nasa/GMSEC_API/commit/f6d7c49b15564dfef1dc79b90ae71788a216792d) were made to the templates, and API 4.9.1 (among others) were re-built and replaced the existing published releases.

I am now seeing the following error in init:
```
gov.nasa.gsfc.gmsec.api.GMSEC_Exception: [13,104,0]: Template Directory information failed to load: [13,107,0] : DIRECTORY is missing definition for LEVEL-1 HEADER
	at gov.nasa.gsfc.gmsec.api.jni.gmsecJNI.new_ConnectionManager(Native Method) ~[gmsec-api-4.9.1.jar:?]
	at gov.nasa.gsfc.gmsec.api.jni.mist.JNIConnectionManager.<init>(JNIConnectionManager.java:113) ~[gmsec-api-4.9.1.jar:?]
	at gov.nasa.gsfc.gmsec.api.mist.ConnectionManager.<init>(ConnectionManager.java:111) ~[gmsec-api-4.9.1.jar:?]
```

As an aside, I would not have expected released artifacts to change once released...

**Comment by bpfoster** [comment]
[This commit](https://github.com/nasa/GMSEC_API/commit/0fed2ef2cd27338540f0ec15e37a33f0a17d8cda) was also applied to the re-released package as a number of template xsd files are missing from it.

**Comment by dmwhitne-583** [comment]
Hello Ben,

I have been instructed by NASA management to remove certain message templates from the open-source distributions of the GMSEC API, including within those that were posted in the past. I have amended the latest README file to include the following, which provides instructions that you can use to move forward:

All C2MS-PIPE (formerly known as C2MS-11b) and GMSEC message templates have been
removed from the open-source distributions of the GMSEC API, including within
releases posted in the past. If attempting to use releases 4.5 through 4.9.1,
pass the gmsec-schema-level=0 configuration option when instantiating a
Connection or ConnectionManager object. This will load C2MS message templates.
If C2MS-PIPE or GMSEC message templates are required, please send a request to
gmsec-support@lists.nasa.gov for further guidance on how to acquire these.

I hope this info will assist you with your use of the GMSEC API.

**Comment by bpfoster** [comment]
Yes, thank you that does resolve the error.
